export const ActionTypes = {
    GET_DATABASE_REQUEST: 'GET_DATABASE_REQUEST',
    GET_DATABASE_SUCCESS: 'GET_DATABASE_SUCCESS',
    GET_DATABASE_FAILED: 'GET_DATABASE_FAILED',

    GET_DATA_REQUEST: 'GET_DATA_REQUEST',
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    GET_DATA_FAILED: 'GET_DATA_FAILED',
}